pub mod functn_sneaky_unsafe_arg;
pub mod functn_sneaky_unsafe_fn_expr_none_args;
pub mod functn_sneaky_unsafe_fn_expr_some_args;

pub mod method_sneaky_unsafe_arg;
pub mod method_sneaky_unsafe_self_none_args;
pub mod method_sneaky_unsafe_self_some_args;
