# - KEEP this in sync with ../../tests-run.sh
# - BUT, ../../tests-run.sh needs to undo any effects of directory change (`cd`), while here each
#   GitHub action step starts in the repository directory

name: Tests, doc tests, MIRI, violations coverage

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    # We need at least Rust 1.89.0 - contrary to "rust-version" (MSRV) in Cargo.toml.
    #
    # Our tests use usize::unchecked_add, which was stabilized in Rust 1.79.
    #
    # With Rust 1.88.0 or older, we were getting false positive errors from `cargo test`, reporting
    # constants in doctests (like `const B: bool = true` in README.md) as unused, even though they
    # were used.
    #
    # https://hub.docker.com/_/rust/tags?name=alpine&ordering=-last_updated&page=17
    container: rust:1.89.0-alpine
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: rustup components
        shell: sh
        run: |
          ./tests-setup-rustup.sh
          ./tests-setup-alpine.sh

      - name: tests-run-*.sh
        shell: sh
        run: |
          ./tests-run-default.sh
          ./tests-run-nightly.sh
