# - KEEP this in sync with ../../tests-run.sh
# - BUT, ../../tests-run.sh needs to undo any effects of directory change (`cd`), while here each
#   GitHub action step starts in the repository directory

name: Tests, doc tests, MIRI, violations coverage

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    # See "rust-version" (MSRV)https://doc.rust-lang.org/std/macro.include_str.html. But, 1.37 is the oldest Alpine docker image. See
    # https://hub.docker.com/_/rust/tags?name=alpine&ordering=-last_updated.
    #
    # rust:1.37-alpine was failing some GitHub's extra checks:
    # https://github.com/prudent-rs/prudent/actions/runs/18773758118/job/53563574851
    #
    # Other Rust Alpine images that I've tried and they failed: rust:1.54.0-alpine.
    #
    # Also, our tests use usize::unchecked_add, which was stabilized in Rust 1.79.
    #
    # More: With Rust 1.88.0 or older, we were getting false positive errors from `cargo test`,
    # reporting constants in doctests as unused, even though they were used. That's why we need at
    # least 1.89.
    container: rust:1.89.0-alpine
    # TODO rust:1.93-alpine
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: rustup components
        shell: sh
        run: |
          ./tests-setup-rustup.sh
          ./tests-setup-alpine.sh

      - name: tests-run.sh
        shell: sh
        run: ./tests-run.sh
